"""Add title column to sessions

Revision ID: cbe7ca97e713
Revises: cb1fc4cb4885
Create Date: 2025-04-05 14:39:25.288913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe7ca97e713'
down_revision = 'cb1fc4cb4885'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'title')
    # ### end Alembic commands ### 